import { jsPDF } from 'jspdf';
import type { StudyNote, ProblemSolution, QuizResult, QuizQuestion, StudySchedule, UserProfile } from '../types';

// Helper to draw standard branded header for TeachBuddy AI
function drawPdfHeader(doc: jsPDF, documentType: string, studentName?: string) {
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Top Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 28, 'F');
  
  // Accent gradient-like stripe
  doc.setFillColor(79, 70, 229); // indigo-600
  doc.rect(0, 28, pageWidth, 2.5, 'F');
  doc.setFillColor(6, 182, 212); // cyan-500
  doc.rect(0, 29.5, pageWidth * 0.4, 1, 'F');

  // Brand Name & Tagline
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('TeachBuddy AI', 14, 13);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Learn  •  Grow  •  Together   |   AI Student Study Buddy', 14, 21);

  // Document Type Badge / Date
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(226, 232, 240);
  doc.text(documentType.toUpperCase(), pageWidth - 14, 13, { align: 'right' });
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  const dateStr = new Date().toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric'
  });
  doc.text(`${studentName ? `Student: ${studentName}  |  ` : ''}${dateStr}`, pageWidth - 14, 21, { align: 'right' });
  
  // Reset text color for body
  doc.setTextColor(30, 41, 59);
}

// Helper to draw standard branded footer
function drawPdfFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, pageHeight - 12, pageWidth - 14, pageHeight - 12);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by TeachBuddy AI — 24/7 Interactive Student Mentor', 14, pageHeight - 7);
  doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 14, pageHeight - 7, { align: 'right' });
}

// 1. EXPORT STUDY NOTES TO PDF
export function exportStudyNotesToPdf(note: StudyNote, studentName: string = 'Student'): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  
  let currentY = 38;

  function checkPageBreak(neededHeight: number) {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      drawPdfHeader(doc, 'Revision Notes', studentName);
      currentY = 38;
    }
  }

  // Draw First Page Header
  drawPdfHeader(doc, 'Revision Notes', studentName);

  // Title Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, currentY, contentWidth, 22, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(note.topic, margin + 4, currentY + 8);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const metaText = `Subject: ${note.subject}   |   Chapter: ${note.chapter}   |   Unit: ${note.unit || 'Unit 1'}   |   Stage: ${note.ageGroup.replace('_', ' ')}`;
  doc.text(metaText, margin + 4, currentY + 16);

  currentY += 28;

  // 1. Summary Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(67, 56, 202); // indigo-700
  doc.text('1. EXECUTIVE CONCEPT SUMMARY', margin, currentY);
  currentY += 5;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(note.summary, contentWidth);
  checkPageBreak(summaryLines.length * 5 + 6);
  doc.text(summaryLines, margin, currentY);
  currentY += summaryLines.length * 5 + 6;

  // 2. High-Yield Key Points
  if (note.bulletPoints && note.bulletPoints.length > 0) {
    checkPageBreak(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text('2. CORE KEY POINTS & PRINCIPLES', margin, currentY);
    currentY += 5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);

    note.bulletPoints.forEach((point) => {
      const bulletLines = doc.splitTextToSize(`• ${point}`, contentWidth - 4);
      checkPageBreak(bulletLines.length * 4.5 + 2);
      doc.text(bulletLines, margin + 2, currentY);
      currentY += bulletLines.length * 4.5 + 2;
    });
    currentY += 4;
  }

  // 3. Formulas & Key Terms Glossary
  if (note.formulasAndKeyTerms && note.formulasAndKeyTerms.length > 0) {
    checkPageBreak(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text('3. FORMULA & KEY DEFINITIONS GLOSSARY', margin, currentY);
    currentY += 6;

    note.formulasAndKeyTerms.forEach((item) => {
      const termHeight = 12;
      checkPageBreak(termHeight);
      
      // Item Box
      doc.setFillColor(241, 245, 249);
      doc.roundedRect(margin, currentY, contentWidth, 10, 2, 2, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(item.term, margin + 3, currentY + 6);

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(51, 65, 85);
      const defLines = doc.splitTextToSize(item.definition, contentWidth - 65);
      doc.text(defLines[0] || '', margin + 60, currentY + 6);

      currentY += 12;
    });
    currentY += 4;
  }

  // 4. Mindmap Architecture Outline
  if (note.mindmapOutline && note.mindmapOutline.length > 0) {
    checkPageBreak(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text('4. CONCEPT MINDMAP & TOPIC HIERARCHY', margin, currentY);
    currentY += 6;

    note.mindmapOutline.forEach((branch) => {
      checkPageBreak(12);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(30, 41, 59);
      doc.text(`▸ ${branch.main}:`, margin + 2, currentY);
      currentY += 4.5;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);
      const subs = branch.subtopics.join('  |  ');
      const subLines = doc.splitTextToSize(`   ↳ ${subs}`, contentWidth - 6);
      doc.text(subLines, margin + 4, currentY);
      currentY += subLines.length * 4 + 3;
    });
    currentY += 4;
  }

  // 5. Practice Exam Questions
  if (note.practiceQuestions && note.practiceQuestions.length > 0) {
    checkPageBreak(15);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text('5. PRACTICE DRILLS & EXAM QUESTIONS', margin, currentY);
    currentY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85);

    note.practiceQuestions.forEach((q, idx) => {
      const qLines = doc.splitTextToSize(`Q${idx + 1}. ${q}`, contentWidth - 4);
      checkPageBreak(qLines.length * 4.5 + 2);
      doc.text(qLines, margin + 2, currentY);
      currentY += qLines.length * 4.5 + 2;
    });
  }

  // Apply footers to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPdfFooter(doc, i, totalPages);
  }

  const safeFilename = `${note.topic.replace(/[^a-zA-Z0-9]/g, '_')}_TeachBuddyAI_Notes.pdf`;
  doc.save(safeFilename);
}

// 2. EXPORT STEP-BY-STEP PROBLEM SOLUTION TO PDF
export function exportProblemSolutionToPdf(sol: ProblemSolution, studentName: string = 'Student'): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  
  let currentY = 38;

  function checkPageBreak(neededHeight: number) {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      drawPdfHeader(doc, 'Problem Solution', studentName);
      currentY = 38;
    }
  }

  drawPdfHeader(doc, 'Problem Solution', studentName);

  // Problem Box
  doc.setFillColor(243, 244, 246);
  doc.setDrawColor(209, 213, 219);
  doc.roundedRect(margin, currentY, contentWidth, 24, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(17, 24, 39);
  doc.text(`Subject: ${sol.subject}  |  Difficulty: ${sol.difficulty}`, margin + 4, currentY + 6);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(55, 65, 81);
  const probLines = doc.splitTextToSize(`Problem: "${sol.problemText}"`, contentWidth - 8);
  doc.text(probLines.slice(0, 3), margin + 4, currentY + 12);

  currentY += 29;

  // Given Data & Concepts
  if (sol.givenData && sol.givenData.length > 0) {
    checkPageBreak(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(147, 51, 234); // purple-600
    doc.text('GIVEN CONDITIONS & DATA:', margin, currentY);
    currentY += 4.5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(55, 65, 81);
    doc.text(sol.givenData.join('   •   '), margin + 2, currentY);
    currentY += 7;
  }

  // Step-by-Step Breakdown
  checkPageBreak(15);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(147, 51, 234);
  doc.text('STEP-BY-STEP MATHEMATICAL SOLUTION', margin, currentY);
  currentY += 6;

  sol.stepByStep.forEach((step) => {
    checkPageBreak(22);
    doc.setFillColor(250, 245, 255); // purple-50
    doc.setDrawColor(233, 213, 255);
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(88, 28, 135);
    doc.text(`Step ${step.stepNumber}: ${step.title}`, margin + 3, currentY + 4);
    currentY += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(55, 65, 81);
    const expLines = doc.splitTextToSize(step.explanation, contentWidth - 6);
    doc.text(expLines, margin + 3, currentY);
    currentY += expLines.length * 4.2;

    if (step.formulaOrCode) {
      doc.setFont('courier', 'bold');
      doc.setFontSize(8.5);
      doc.setTextColor(126, 34, 206);
      doc.text(`  > ${step.formulaOrCode}`, margin + 3, currentY + 2);
      currentY += 6;
    }
    currentY += 4;
  });

  // Final Answer Highlight Box
  checkPageBreak(18);
  doc.setFillColor(236, 253, 245); // emerald-50
  doc.setDrawColor(52, 211, 153);
  doc.roundedRect(margin, currentY, contentWidth, 14, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(6, 95, 70);
  doc.text(`FINAL ANSWER: ${sol.finalAnswer}`, margin + 4, currentY + 9);
  currentY += 18;

  // Pro Tips & Pitfalls
  if (sol.proTips && sol.proTips.length > 0) {
    checkPageBreak(14);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9.5);
    doc.setTextColor(217, 119, 6);
    doc.text('EXAM SPEED TRICK & PRO TIPS:', margin, currentY);
    currentY += 4.5;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(75, 85, 99);
    sol.proTips.forEach((tip) => {
      const tipLines = doc.splitTextToSize(`★ ${tip}`, contentWidth - 4);
      doc.text(tipLines, margin + 2, currentY);
      currentY += tipLines.length * 4 + 1;
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPdfFooter(doc, i, totalPages);
  }

  doc.save(`Solution_TeachBuddyAI_${Date.now()}.pdf`);
}

// 3. EXPORT QUIZ SCORECARD REPORT TO PDF
export function exportQuizResultToPdf(
  result: QuizResult, 
  questions: QuizQuestion[], 
  studentName: string = 'Student'
): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  
  let currentY = 38;

  function checkPageBreak(neededHeight: number) {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      drawPdfHeader(doc, 'Quiz Scorecard', studentName);
      currentY = 38;
    }
  }

  drawPdfHeader(doc, 'Quiz Scorecard', studentName);

  // Score Summary Banner
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, currentY, contentWidth, 26, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`Topic: ${result.topic}`, margin + 4, currentY + 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  const isPassing = result.percentage >= 60;
  doc.setTextColor(isPassing ? 16 : 220, isPassing ? 185 : 38, isPassing ? 129 : 38);
  doc.text(`${result.score} / ${result.totalQuestions}  (${result.percentage}%)`, pageWidth - margin - 6, currentY + 11, { align: 'right' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Time Spent: ${Math.round(result.timeSpentSeconds)}s   |   XP Earned: +${result.xpEarned} XP   |   Status: ${isPassing ? 'PASSED' : 'REVISION NEEDED'}`, margin + 4, currentY + 18);

  currentY += 32;

  // Questions Review Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(67, 56, 202);
  doc.text('QUESTION-BY-QUESTION BREAKDOWN', margin, currentY);
  currentY += 6;

  questions.forEach((q, idx) => {
    const userAnswerIndex = result.userAnswers ? result.userAnswers[idx] : -1;
    const isCorrect = userAnswerIndex === q.correctIndex;

    checkPageBreak(25);

    // Question box
    doc.setFillColor(isCorrect ? 240 : 254, isCorrect ? 253 : 242, isCorrect ? 244 : 242);
    doc.setDrawColor(isCorrect ? 187 : 254, isCorrect ? 247 : 202, isCorrect ? 208 : 202);
    doc.roundedRect(margin, currentY, contentWidth, 8, 2, 2, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(isCorrect ? 21 : 185, isCorrect ? 128 : 28, isCorrect ? 61 : 28);
    doc.text(`${isCorrect ? '✓ CORRECT' : '✗ INCORRECT'} — Q${idx + 1}:`, margin + 3, currentY + 5.5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    const qShort = doc.splitTextToSize(q.question, contentWidth - 45);
    doc.text(qShort[0] || '', margin + 35, currentY + 5.5);
    currentY += 10;

    // Correct Answer & Explanation
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(`Correct Option: "${q.options[q.correctIndex]}"`, margin + 4, currentY);
    currentY += 4;

    const expLines = doc.splitTextToSize(`Explanation: ${q.explanation}`, contentWidth - 8);
    doc.text(expLines, margin + 4, currentY);
    currentY += expLines.length * 3.8 + 4;
  });

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPdfFooter(doc, i, totalPages);
  }

  doc.save(`QuizScore_${result.topic.replace(/[^a-zA-Z0-9]/g, '_')}_TeachBuddyAI.pdf`);
}

// 4. EXPORT STUDY SCHEDULE TO PDF
export function exportScheduleToPdf(schedule: StudySchedule, studentName: string = 'Student'): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  
  let currentY = 38;

  function checkPageBreak(neededHeight: number) {
    if (currentY + neededHeight > pageHeight - 20) {
      doc.addPage();
      drawPdfHeader(doc, 'Study Timetable', studentName);
      currentY = 38;
    }
  }

  drawPdfHeader(doc, 'Study Timetable', studentName);

  // Title Box
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, currentY, contentWidth, 20, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text(schedule.title || 'Personalized Study Timetable', margin + 4, currentY + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Target Goal: ${schedule.targetGoal}   |   Hours/Day: ${schedule.hoursPerDay}h   |   Duration: ${schedule.totalDays} Days   ${schedule.examDate ? `| Exam: ${schedule.examDate}` : ''}`, margin + 4, currentY + 14);

  currentY += 26;

  // Table Header
  doc.setFillColor(15, 23, 42);
  doc.rect(margin, currentY, contentWidth, 8, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(255, 255, 255);
  doc.text('DAY & TIME', margin + 3, currentY + 5.5);
  doc.text('SUBJECT & TOPIC', margin + 45, currentY + 5.5);
  doc.text('ACTIVITY TYPE', margin + 120, currentY + 5.5);
  doc.text('STATUS', margin + 160, currentY + 5.5);

  currentY += 9;

  schedule.tasks.forEach((task, idx) => {
    checkPageBreak(12);

    // Row alternating background
    if (idx % 2 === 1) {
      doc.setFillColor(248, 250, 252);
      doc.rect(margin, currentY - 1, contentWidth, 9, 'F');
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(15, 23, 42);
    doc.text(`${task.day}`, margin + 3, currentY + 3);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(100, 116, 139);
    doc.text(`${task.timeSlot}`, margin + 3, currentY + 7);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(30, 41, 59);
    doc.text(`${task.subject}: ${task.topic}`.slice(0, 42), margin + 45, currentY + 4.5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(79, 70, 229);
    doc.text(`${task.activityType} (${task.durationMinutes}m)`, margin + 120, currentY + 4.5);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(task.completed ? 16 : 148, task.completed ? 185 : 163, task.completed ? 129 : 184);
    doc.text(task.completed ? '[✓ Done]' : '[  ] Pending', margin + 160, currentY + 4.5);

    currentY += 10;
  });

  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawPdfFooter(doc, i, totalPages);
  }

  doc.save(`StudyPlan_TeachBuddyAI_${Date.now()}.pdf`);
}

// 5. EXPORT STUDENT PROGRESS REPORT & CERTIFICATE
export function exportStudentReportToPdf(user: UserProfile): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const contentWidth = pageWidth - margin * 2;
  
  let currentY = 38;

  drawPdfHeader(doc, 'Student Performance Report', user.name);

  // Student Profile Card
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(203, 213, 225);
  doc.roundedRect(margin, currentY, contentWidth, 32, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(user.name, margin + 6, currentY + 10);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(71, 85, 105);
  doc.text(`Stage: ${user.ageGroup.replace('_', ' ')}   |   Institution: ${user.institution}   |   Account: ${user.isPremium ? 'PRO Member' : 'Standard Scholar'}`, margin + 6, currentY + 18);
  doc.text(`Email: ${user.email || 'Student Account'}   |   Member Since: ${new Date(user.createdAt).toLocaleDateString()}`, margin + 6, currentY + 25);

  currentY += 38;

  // Key Metrics Grid
  const colWidth = (contentWidth - 6) / 3;

  // Metric 1: Total XP & Level
  doc.setFillColor(238, 242, 255); // indigo-50
  doc.roundedRect(margin, currentY, colWidth, 24, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(79, 70, 229);
  doc.text('TOTAL EXPERIENCE (XP)', margin + 4, currentY + 7);
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`${user.xp || 0} XP`, margin + 4, currentY + 15);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`Level ${user.level || 1} Scholar`, margin + 4, currentY + 20);

  // Metric 2: Daily Streak
  doc.setFillColor(255, 247, 237); // orange-50
  doc.roundedRect(margin + colWidth + 3, currentY, colWidth, 24, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(234, 88, 12);
  doc.text('DAILY STUDY STREAK', margin + colWidth + 7, currentY + 7);
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`${user.streakDays || 1} Days`, margin + colWidth + 7, currentY + 15);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Active Habit Builder', margin + colWidth + 7, currentY + 20);

  // Metric 3: Badges Unlocked
  doc.setFillColor(240, 253, 244); // emerald-50
  doc.roundedRect(margin + (colWidth + 3) * 2, currentY, colWidth, 24, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(22, 163, 74);
  doc.text('BADGES & ACHIEVEMENTS', margin + (colWidth + 3) * 2 + 4, currentY + 7);
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text(`${user.badges?.length || 2} Badges`, margin + (colWidth + 3) * 2 + 4, currentY + 15);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text('Milestones Claimed', margin + (colWidth + 3) * 2 + 4, currentY + 20);

  currentY += 32;

  // Unlocked Badges List
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(79, 70, 229);
  doc.text('ACHIEVEMENT BADGES UNLOCKED', margin, currentY);
  currentY += 6;

  (user.badges || ['Curious Mind', 'Fast Learner']).forEach((badge) => {
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, currentY, contentWidth, 9, 2, 2, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.setTextColor(30, 41, 59);
    doc.text(`★  ${badge}`, margin + 4, currentY + 6);
    currentY += 11;
  });

  currentY += 6;

  // Teacher Remarks / AI Buddy Note
  doc.setFillColor(245, 243, 255);
  doc.setDrawColor(196, 181, 253);
  doc.roundedRect(margin, currentY, contentWidth, 26, 3, 3, 'FD');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(109, 40, 217);
  doc.text('TEACHBUDDY AI MENTOR REMARKS:', margin + 4, currentY + 7);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const remarks = `${user.name} has demonstrated remarkable learning curiosity, maintaining active study streaks and leveraging AI voice call sessions to master concepts thoroughly. Keep building the daily habit!`;
  const remarkLines = doc.splitTextToSize(remarks, contentWidth - 8);
  doc.text(remarkLines, margin + 4, currentY + 14);

  drawPdfFooter(doc, 1, 1);
  doc.save(`StudentReport_${user.name.replace(/[^a-zA-Z0-9]/g, '_')}_TeachBuddyAI.pdf`);
}

// Convenient alias for singular naming
export const exportStudyNoteToPdf = exportStudyNotesToPdf;
